### ISSUE TITLE
Installation Issue (not open admin url )

### ISSUE THREAD

**Issue by javedalam86** [DivanteLtd/open-loyalty#118]
_Hi,_

I followed as per your installation document for Window 10 like below command 

Installed Vagrant and Virtualbox prior to executing this recipe.

Then followed below commands:

**vagrant up
vagrant ssh
docker-compose -f docker/docker-compose.yml up -d
docker-compose -f docker/docker-compose.yml exec php phing setup**

everything installed successfully and i am facing same issues for older version and latest version code as per attached screen. Kindly suggest what other configuration required to update.
![error_1](https://user-images.githubusercontent.com/19759533/43116325-92832302-8ef6-11e8-8fb8-d1aa21260b3b.png)

Thank you.

**Comment by mohan-nishit** [comment]
> docker-compose -f docker/docker-compose.yml up -d
requires some time before the app is ready to use. If you don't use the -d switch, you can see the verbose output which tells you whether the app is ready. Of course, then the script will need to be sent to background and disowned (ctrl + z, bg and disown)

**Comment by javedalam86** [comment]
Thanks for your update. After running **docker-compose -f docker/docker-compose.yml up -d** I waited log time duration (around 3 to 4 hours ) but its still have same issue. Please let me know if there is any other option to resolve it. Thank you

**Comment by Sharatheywa** [comment]
I'm also having the same issue. Need help please.

**Comment by colejarczyk** [comment]
Hi,

@Sharatheywa can you run command with "-d" parameter and provide and output to see is there any problem?

After that, call "docker-compose -f docker/docker-compose.yml ps" and provide an output too.

**Comment by Sharatheywa** [comment]
Hi @colejarczyk 

sudo docker-compose -f docker/docker-compose.yml up -d
openloyalty_mail is up-to-date
openloyalty_elk is up-to-date
openloyalty_db is up-to-date
openloyalty_backend is up-to-date
openloyalty_frontend is up-to-date




sudo docker-compose -f docker/docker-compose.yml ps   
        Name                      Command               State                                             Ports                                           
----------------------------------------------------------------------------------------------------------------------------------------------------------
openloyalty_backend    docker-php-entrypoint ./in ...   Up      9000/tcp                                                                                  
openloyalty_db         docker-entrypoint.sh postgres    Up      5432/tcp                                                                                  
openloyalty_elk        /docker-entrypoint.sh elas ...   Up      9200/tcp, 9300/tcp                                                                        
openloyalty_frontend   nginx -g daemon off;             Up      0.0.0.0:8182->3001/tcp, 0.0.0.0:8183->3002/tcp, 0.0.0.0:8184->3003/tcp, 0.0.0.0:80->80/tcp
openloyalty_mail       MailHog                          Up      1025/tcp, 0.0.0.0:8186->8025/tcp

**Comment by colejarczyk** [comment]
Hi @Sharatheywa 

Seems like all docker containers are up.

Can you try visit http://openloyalty.localhost/app_dev.php/doc ?

**Comment by ruslanguns** [comment]
its failing to me so

![image](https://user-images.githubusercontent.com/19806968/61981952-1d008d80-aff3-11e9-91f4-dc08877383b9.png)

Just recreated it on a DigitalOcean Dropplet to allow to reproduce the issue.


http://167.71.50.114
http://167.71.50.114:8182/#!/

**Comment by ruslanguns** [comment]
by the way also getting this in the root:
`

Fatal error: Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in /var/www/openloyalty/var/cache/prod/appProdProjectContainerUrlMatcher.php:2747 Stack trace: #0 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/Routing/Matcher/UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/app_dev.php/do...') #1 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object in /var/www/openloyalty/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 75
`

**Comment by colejarczyk** [comment]
@javedalam86 seems like "openloyalty.localhost" domain is not configured on your computer to point to the localhost. If you are using Windows, add it to the C:\Windows\System32\Drivers\etc\hosts or in Linux edit /etc/hosts

openloyalty.localhost 127.0.0.1

@ruslanguns you need to initialize a project by calling "docker-compose -f docker/docker-compose.yml exec --user=www-data php phing setup"

**Comment by comeseecomesav** [comment]
Ive done all of these steps but it looks like docker is failing to build anything in var/www.

**Comment by ruslanguns** [comment]
@colejarczyk thanks for your response... sorry for getting late, I always have issues with Github notifications...

- Still fails but with another error: 

![image](https://user-images.githubusercontent.com/19806968/63219277-2ac6b000-c166-11e9-83d4-a80d6fcef185.png)

**Comment by jural** [comment]
Hi,

I don't know what you have configured on 81 port, but if it is API try to add /doc to URl, because root location is not configured and always returns 404.

**Comment by jenoOvchi** [comment]
Hi,
I have been started docker compose on the remote machine and have the same issue until insert line from the instruction (<remote-host-ip> openloyalty.localhost) to /etc/hosts of my local machine. But it's not good way to hardcode hosts and i have been found workaround. You just need to copy file config.js (https://github.com/DivanteLtd/open-loyalty/blob/master/frontend/src/config.js) from openloyalty_frontend container (/var/www/openloyalty/front/config.js), change "openloyalty.localhost" in all "apiUrl" tags (2) for your hostname and mount it to your container. My docker-compose.yml looks as follows (i have been added volumes for Elastic Search and PostgreSQL data too):

```yaml
version: "2"

services:
  php:
    container_name: openloyalty_backend
    image: divante/open-loyalty-fpm
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
        - .env
  nginx:
    container_name: openloyalty_frontend
    image: divante/open-loyalty-web
    volumes:
      - "/opt/open-loyalty/config.js:/var/www/openloyalty/front/config.js"
    links:
      - php
    ports:
      - "80:80"
      - "8182:3001"
      - "8183:3002"
      - "8184:3003"
  elk:
    container_name: openloyalty_elk
    image: divante/open-loyalty-elasticsearch:2.2.0
    volumes:
      - "/opt/open-loyalty/elastic_data:/usr/share/elasticsearch/data"
  db:
    container_name: openloyalty_db
    image: postgres:9
    env_file:
        - .env
    volumes:
      - "/opt/open-loyalty/postgres_data:/var/lib/postgresql/data"
  mail:
    container_name: openloyalty_mail
    image: mailhog/mailhog
    ports:
      - "8186:8025"
```

Now all works fine. I hope it will be helpful for someone.
