### ISSUE TITLE
gcloud kubernetes

### ISSUE THREAD

**Issue by sultanmyrza** [DivanteLtd/open-loyalty#160]
Following instructions https://docs.openloyalty.io/en/latest/developer/installation/kubernetes.html
not clear (for example it has .dockerConfig: _REPLACE_IT) 
```
apiVersion: v1
data:
    .dockerconfigjson: __REPLACE_IT__
kind: Secret
metadata:
    name: registry
    namespace: openloyalty
type: kubernetes.io/dockerconfigjson
```
what should be there? And some other questions. 

Let's please go through and update docs for deploying openloyalty on gcloud (kubernetes).
I think it might be helpful for others too since there are some tickets that were closed (_We do not support Kubernetes yet. However, a lot of people asked about it and how to deploy Open Loyalty on Heroku, Amazon Cloud or Google Cloud we plan to add support for Kubernetes in near future_).

So maybe the time has come? I hope it will be also useful for other devs who just want to try out openloyalty. If needed I can also (would be happy to) contribute to docs and share the journey and add to your docs (kubernetes gcloud section)

Right now
I'm trying to deploy dev version of open loyalty on gcloud (kubernetes)

I stuck at gcloud kubectl create -f deployment.yml
What I did 
1. create cluster in gcloud
2. kubectl create namespace openloyalty
3. pull openloyalty to gcloud, go to openloyalty/kubernetes dir
4. kubectl create -f storage.yml [success]
5. kubectl create -f claims.yml [success]
6. kubectl create -f config.yml [success]
7. kubectl create -f deployment.yml [error]

```
deployment.extensions/db created
service/db created
deployment.extensions/web created
error: error validating "deployment.yml": error validating data: ValidationError(Service.spec.externalIPs[0]): invalid type for io.k8s.api.core.v1.ServiceSpec.externalIPs: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
```

I check docs again and found out that 

i also have to run this command `kubectl -n openloyalty apply -f pv.yml` but there is no pv.yml maybe docs bit outdated.
```
apiVersion: v1
data:
    .dockerconfigjson: __REPLACE_IT__ <----- what I should put here?
kind: Secret
metadata:
    name: registry
    namespace: openloyalty
type: kubernetes.io/dockerconfigjson
```

Please lets do the docs for kubernetes gloud version
