### ISSUE TITLE
issue after running composer install

### ISSUE THREAD

**Issue by fadlikhalid** [DivanteLtd/open-loyalty#163]
![image](https://user-images.githubusercontent.com/58224360/71498357-00fd6280-2897-11ea-856e-50c378d255d3.png)

 

> Compile Error: Declaration of CouponUsageProjector_341f57e::handle(Broadway
>   \Domain\DomainMessage $domainMessage) must be compatible with OpenLoyalty\C
>   omponent\Campaign\Infrastructure\ReadModel\CouponUsageProjector::handle(Bro
>   adway\Domain\DomainMessage $domainMessage): void

> Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

> [RuntimeException]
>   An error occurred when executing the "'cache:clear --no-warmup'" command:
>   PHP Fatal error:  Declaration of CouponUsageProjector_341f57e::handle(Broadway\Domain\DomainMessage $domainMessage) must be compatible with OpenLoyalty\Component\Campaign\I
>   nfrastructure\ReadModel\CouponUsageProjector::handle(Broadway\Domain\DomainMessage $domainMessage): void in /var/www/openloyalty-bak/var/cache/dev/ContainerS1xisoh/CouponUs
>   ageProjector_341f57e.php on line 3
>   In CouponUsageProjector_341f57e.php line 3:
> 
>     Compile Error: Declaration of CouponUsageProjector_341f57e::handle(Broadway
>     \Domain\DomainMessage $domainMessage) must be compatible with OpenLoyalty\C
>     omponent\Campaign\Infrastructure\ReadModel\CouponUsageProjector::handle(Bro
>     adway\Domain\DomainMessage $domainMessage): void

Hi all, pardon me for asking this. But I'm stuck right now.
I've tried setting this open loyalty up without using docker on CentOS.
But currently, while running the _composer install --no-dev --prefer-dist_ it shows this error.
Can someone help me on this?

**Comment by colejarczyk** [comment]
@fadlikhalid which version of PHP have you installed on CentOS? If higher than 7.1 then that won't work.

**Comment by fadlikhalid** [comment]
aahh. i see. i think 7.2 okay then. will try with lower version of php

**Comment by fadlikhalid** [comment]
@colejarczyk how about this?

![image](https://user-images.githubusercontent.com/58224360/71559817-8a7e8180-2a9d-11ea-9806-cf65e51b5b89.png)

> [console] Error thrown while running command "doctrine:schema:update --env=prod -n --force". Message: "An exception occured in driver: could not find driver" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "doctrine:schema:update --env=prod -n --force","message" => "An exception occured in driver: could not find driver"] []

> In AbstractPostgreSQLDriver.php line 91: An exception occured in driver: could not find driver

> In PDOConnection.php line 47:  could not find driver

> In PDOConnection.php line 43:  could not find driver


I'm using postgres 9.6.16 at the moment.

and this is my parameters.yml
![image](https://user-images.githubusercontent.com/58224360/71560030-8fdccb80-2a9f-11ea-8b9b-7e57f752f50f.png)

what could possibly cause the error mentioned above?

Thank you in advance.

**Comment by fadlikhalid** [comment]
ahh. nvm. it seems that i haven't installed the pgsql driver.

but now got new issue.

![image](https://user-images.githubusercontent.com/58224360/71560230-1692a800-2aa2-11ea-9f56-a769b4b4fcb4.png)

**Comment by colejarczyk** [comment]
@fadlikhalid which version of Elasticsearch do you use?

**Comment by fadlikhalid** [comment]
> @fadlikhalid which version of Elasticsearch do you use?

6.2.4

also, when i run the command bin/console --version,
i get this
> Symfony 3.4.14 (kernel: app, env: dev, debug: true)

but when i run it in my docker container, i got this
>Symfony 3.4.14 (kernel: app, env: prod, debug: false)

The thing is, the one run on CentOS got all files taken from the docker container. 
Was that the cause?

**Comment by colejarczyk** [comment]
@fadlikhalid you have to use dependencies in exact version as stated in dockerfiles

https://github.com/DivanteLtd/open-loyalty/blob/master/docker/base/elasticsearch-dockerfile

in this case, Elastic Search 2.2

**Comment by fadlikhalid** [comment]
> @fadlikhalid you have to use dependencies in exact version as stated in dockerfiles
> 
> https://github.com/DivanteLtd/open-loyalty/blob/master/docker/base/elasticsearch-dockerfile
> 
> in this case, Elastic Search 2.2

Thanks. I will try it now

**Comment by fadlikhalid** [comment]
Thank you @colejarczyk for you assistance. I've managed to run the phing setup with no issue after changing the Elasticsearch to 2.2.2.

But now, i got this problem.

![image](https://user-images.githubusercontent.com/58224360/71610104-21942800-2bc9-11ea-8cc9-539b6b753f91.png)

May i know how the frontend connect to backend?

**Comment by pawelabrams** [comment]
Can you check if the address is available for a direct request? That is, if you can access http://190.100.10.68/api/translations manually?

If you can, this is because of a lack of CORS headers on API endpoints in the development build; in production, the developer is expected to add them themselves.

For development purposes, adding `Access-Control-Allow-Origin: *` would be fine, for production you'll want to change the asterisk to an address/domain name containing the admin panel.

To add such a header automatically, find the nginx configuration (in a docker build, it's the file named `backend.conf` or similar in the directory `/etc/nginx/conf.d/`) and add a following line above `internal;` keyword, inside a `location` block that has `.php` in its selector:

```
add_header 'Access-Control-Allow-Origin' '*';
```

**Comment by sultanmyrza** [comment]
Have similar issue POST http://35.185.140.61/api/admin/login_check 500 (Internal Server Error)

is that related to this [commit](https://github.com/DivanteLtd/open-loyalty/commit/31c5bc5bd4207f36f0449b113d826d4ca11aac24)?

I deploy on gcloud ubuntu before it worked well but maybe after that commit its broken

while deploying I have this issue
https://i.imgur.com/i0PJwF1.png

even I can open admin page now I have this issue and can not login to admin panel
https://i.imgur.com/4bVMePY.png
however http://35.185.140.61/api/translations is working fine
I use login admin password open

my docker-compose.yml
```
version: "2"

services:
  php:
    container_name: openloyalty_backend
    image: divante/open-loyalty-fpm
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - frontend_customer_panel_url=http://35.185.140.61:8183/client
      - frontend_password_reset_url=35.185.140.61:8183/client#!/password/reset
  nginx:
    container_name: openloyalty_frontend
    image: divante/open-loyalty-web
    links:
      - php
    ports:
      - "80:80"
      - "8182:3001"
      - "8183:3002"
      - "8184:3003"
    command: bash -c "sed -i -e 's@"http://openloyalty.localhost/api"@'\"http://35.185.140.61/api\"'@g' /var/www/openloyalty/front/config.js && nginx -g 'daemon off;'"
  elk:
    container_name: openloyalty_elk
    image: divante/open-loyalty-elasticsearch:2.2.0
  db:
    container_name: openloyalty_db
    image: postgres:9
    env_file:
      - .env
  mail:
    container_name: openloyalty_mail
    image: mailhog/mailhog
    ports:
      - "8186:8025"
```

my docker/dev/web/backend.conf
```
server {
    server_name http://35.185.140.61;
    root /var/www/openloyalty/web;
    listen 80;
    client_max_body_size 10m;

    location / {
        add_header 'Access-Control-Allow-Origin' '*';
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    # DEV
    # This rule should only be placed on your development environment
    # In production, don't include this and don't deploy app_dev.php or config.php
    location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }


    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/openloyalty_error.log;
    access_log /var/log/nginx/openloyalty_access.log;
}
```
