### ISSUE TITLE
Can not login after installation

### ISSUE THREAD

**Issue by nejatian** [DivanteLtd/open-loyalty#166]
I have problem in developer mode, the login page show up but I can not login and terminal shows this messages:
openloyalty_backend | php-fpm stderr | 172.18.0.6 -  03/Feb/2020:09:26:08 +0000 "OPTIONS /app.php" 200
openloyalty_backend | php-fpm stderr | 172.18.0.6 -  03/Feb/2020:09:26:08 +0000 "OPTIONS /app.php" 200
openloyalty_backend | php-fpm stderr | 172.18.0.6 -  03/Feb/2020:09:26:08 +0000 "OPTIONS /app.php" 200
openloyalty_backend | php-fpm stderr | 172.18.0.6 -  03/Feb/2020:09:26:08 +0000 "OPTIONS /app.php" 200
openloyalty_backend | php-fpm stderr | 172.18.0.6 -  03/Feb/2020:09:26:08 +0000 "OPTIONS /app.php" 200
openloyalty_backend | php-fpm stderr | 172.18.0.6 -  03/Feb/2020:09:26:08 +0000 "OPTIONS /app.php" 200
openloyalty_backend | php-fpm stderr | 172.18.0.6 -  03/Feb/2020:09:26:08 +0000 "OPTIONS /app.php" 200
openloyalty_backend | php-fpm stderr | 172.18.0.6 -  03/Feb/2020:09:26:08 +0000 "OPTIONS /app.php" 200

**Comment by colejarczyk** [comment]
@tjurczak

**Comment by pawelabrams** [comment]
Hey, @nejatian !

The server probably doesn't receive your messages (no POST logs) because the browser doesn't send them. You can inspect the communication between the client and the server using your browser's tools (commonly accessed by F12 or inspecting any element and going to the network tab).

Having so many OPTIONS pre-flight requests and no POST might mean that the browser refused to contact server because of cross-origin resource sharing policy. This might happen when the address openloyalty.localhost is not recognized as local, as the development server does not send CORS headers out of the box.

There are two possible solutions:
1. add `openloyalty.localhost 127.0.0.1` to your /etc/hosts file if you're on Mac or Linux; or:
2. add `add_header 'Access-Control-Allow-Origin' '*';` to the nginx configuration of the build – it should be in  `open-loyalty/docker/dev/web/backend.conf` . Place the directive before `# try to serve file directly, fallback to app.php` line. After saving, restart the project with rebuild (your usual command ending with `up` + `--build` flag, f.e. `docker-compose -f docker-compose.dev.yml up --build`).

Hope it solves your problem!

**Comment by pawelabrams** [comment]
The confirmation that the browser refuses to connect to server because of CORS should be visible in the Console, similar to what fadlikhalid encountered in https://github.com/DivanteLtd/open-loyalty/issues/163 : https://github.com/DivanteLtd/open-loyalty/issues/163#issuecomment-569861690 .

**Comment by sultanmyrza** [comment]
Have similar issue POST http://35.185.140.61/api/admin/login_check 500 (Internal Server Error)

is that related to this [commit](https://github.com/DivanteLtd/open-loyalty/commit/31c5bc5bd4207f36f0449b113d826d4ca11aac24)?

I deploy on gcloud ubuntu before it worked well but maybe after that commit its broken

while deploying I have this issue
https://i.imgur.com/i0PJwF1.png

even I can open admin page now I have this issue and can not login to admin panel
https://i.imgur.com/4bVMePY.png
however http://35.185.140.61/api/translations is working fine
I use login admin password open

my docker-compose.yml
```
version: "2"

services:
  php:
    container_name: openloyalty_backend
    image: divante/open-loyalty-fpm
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - frontend_customer_panel_url=http://35.185.140.61:8183/client
      - frontend_password_reset_url=35.185.140.61:8183/client#!/password/reset
  nginx:
    container_name: openloyalty_frontend
    image: divante/open-loyalty-web
    links:
      - php
    ports:
      - "80:80"
      - "8182:3001"
      - "8183:3002"
      - "8184:3003"
    command: bash -c "sed -i -e 's@"http://openloyalty.localhost/api"@'\"http://35.185.140.61/api\"'@g' /var/www/openloyalty/front/config.js && nginx -g 'daemon off;'"
  elk:
    container_name: openloyalty_elk
    image: divante/open-loyalty-elasticsearch:2.2.0
  db:
    container_name: openloyalty_db
    image: postgres:9
    env_file:
      - .env
  mail:
    container_name: openloyalty_mail
    image: mailhog/mailhog
    ports:
      - "8186:8025"
```

my docker/dev/web/backend.conf
```
server {
    server_name http://35.185.140.61;
    root /var/www/openloyalty/web;
    listen 80;
    client_max_body_size 10m;

    location / {
        add_header 'Access-Control-Allow-Origin' '*';
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    # DEV
    # This rule should only be placed on your development environment
    # In production, don't include this and don't deploy app_dev.php or config.php
    location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }


    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/openloyalty_error.log;
    access_log /var/log/nginx/openloyalty_access.log;
}
```
