### ISSUE TITLE
HTTP 500 while logging into admin panel

### ISSUE THREAD

**Issue by pawelabrams** [DivanteLtd/open-loyalty#168]
_Originally posted by @sultanmyrza in https://github.com/DivanteLtd/open-loyalty/issues/166#issuecomment-594514473_

> Have similar issue POST http://35.185.140.61/api/admin/login_check 500 (Internal Server Error)
>
> is that related to this [commit](https://github.com/DivanteLtd/open-loyalty/commit/31c5bc5bd4207f36f0449b113d826d4ca11aac24)?
> 
> I deploy on gcloud ubuntu before it worked well but maybe after that commit its broken
> 
> while deploying I have this issue
> https://i.imgur.com/i0PJwF1.png
> 
> even I can open admin page now I have this issue and can not login to admin panel
> https://i.imgur.com/4bVMePY.png
> however http://35.185.140.61/api/translations is working fine
> I use login admin password open
> 
> my docker-compose.yml
```
version: "2"

services:
  php:
    container_name: openloyalty_backend
    image: divante/open-loyalty-fpm
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - frontend_customer_panel_url=http://35.185.140.61:8183/client
      - frontend_password_reset_url=35.185.140.61:8183/client#!/password/reset
  nginx:
    container_name: openloyalty_frontend
    image: divante/open-loyalty-web
    links:
      - php
    ports:
      - "80:80"
      - "8182:3001"
      - "8183:3002"
      - "8184:3003"
    command: bash -c "sed -i -e 's@"http://openloyalty.localhost/api"@'\"http://35.185.140.61/api\"'@g' /var/www/openloyalty/front/config.js && nginx -g 'daemon off;'"
  elk:
    container_name: openloyalty_elk
    image: divante/open-loyalty-elasticsearch:2.2.0
  db:
    container_name: openloyalty_db
    image: postgres:9
    env_file:
      - .env
  mail:
    container_name: openloyalty_mail
    image: mailhog/mailhog
    ports:
      - "8186:8025"
```
> my docker/dev/web/backend.conf
```
server {
    server_name http://35.185.140.61;
    root /var/www/openloyalty/web;
    listen 80;
    client_max_body_size 10m;

    location / {
        add_header 'Access-Control-Allow-Origin' '*';
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    # DEV
    # This rule should only be placed on your development environment
    # In production, don't include this and don't deploy app_dev.php or config.php
    location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }


    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/openloyalty_error.log;
    access_log /var/log/nginx/openloyalty_access.log;
}
```
