### ISSUE TITLE
Page not loading 

### ISSUE THREAD

**Issue by karamatf** [DivanteLtd/open-loyalty#205]
I followed the document and i am running debian version 8 and the same issue it keeps loading 
please advise http://172.104.157.225:8182/#!/

<img width="780" alt="Capture" src="https://user-images.githubusercontent.com/20407825/113741292-c7eea780-9701-11eb-8a72-47fdc9b76226.PNG">

**Comment by pradeepKsrvastva** [comment]
@karamatf Same problem with me i can see lot of users are facing same issue but they are not interested in resolving or helping any one of us

**Comment by karamatf** [comment]
> @karamatf Same problem with me i can see lot of users are facing same issue but they are not interested in resolving or helping any one of us

I have a full stack devellopper helping me with this but he also seems to give up on this as there seems to be to many errors in this so how do i buy the paid version of this

**Comment by karamatf** [comment]
> @karamatf Same problem with me i can see lot of users are facing same issue but they are not interested in resolving or helping any one of us

Hi Pradeep my full stack developper fixed this issue all together took him some time if u want to fix it he charges but he does the job
http://ec2-3-143-147-8.us-east-2.compute.amazonaws.com:8183/#!/
http://ec2-3-143-147-8.us-east-2.compute.amazonaws.com:8182/#!/

**Comment by pradeepKsrvastva** [comment]
@karamatf  Thats a wonderful news! although i tried logging in admin panel here http://ec2-3-143-147-8.us-east-2.compute.amazonaws.com:8182/#!/ with credentials user:admin , password:open but it dont log in and in console i can see 500 error check attached screenshot you might want to ask your dev to take a look also how much he will charge for installation ?
<img width="1440" alt="Screen Shot 2021-04-08 at 5 07 35 PM" src="https://user-images.githubusercontent.com/3379886/114020257-05337080-988d-11eb-95e0-cb6c4e42449e.png">

**Comment by pradeepKsrvastva** [comment]
@karamatf Also registration over here dont work as well http://ec2-3-143-147-8.us-east-2.compute.amazonaws.com:8183/#!/customer/panel/customer/registration it returns back 400 bad request error

**Comment by karamatf** [comment]
> @karamatf Also registration over here dont work as well http://ec2-3-143-147-8.us-east-2.compute.amazonaws.com:8183/#!/customer/panel/customer/registration it returns back 400 bad request error

Hi Pradeep told him that he said hes still fixing it further but at this point im over 100 usd in man

**Comment by pradeepKsrvastva** [comment]
@karamatf I have been able to run it completely now :) and everything seems to be working have a demo here https://loyaltyshera.aevnour.com:8182/ but i have one question how can we access database of application using a utility for eg on php and mysql we use phpmyadmin what to use for this application any ideas ?

**Comment by karamatf** [comment]
> @karamatf I have been able to run it completely now :) and everything seems to be working have a demo here https://loyaltyshera.aevnour.com:8182/ but i have one question how can we access database of application using a utility for eg on php and mysql we use phpmyadmin what to use for this application any ideas ?

Hi man nicely done u got it working admin login works also what did u do mine i am still figthing it how did u manage to get the login working the admin username is small not caps i will ask my dev dude and tell u

**Comment by karamatf** [comment]
> @karamatf I have been able to run it completely now :) and everything seems to be working have a demo here https://loyaltyshera.aevnour.com:8182/ but i have one question how can we access database of application using a utility for eg on php and mysql we use phpmyadmin what to use for this application any ideas ?

this guy made a cloud manaul let me see if i can follow https://www.youtube.com/watch?v=S9lwey0bSMs

**Comment by karamatf** [comment]
> @karamatf I have been able to run it completely now :) and everything seems to be working have a demo here https://loyaltyshera.aevnour.com:8182/ but i have one question how can we access database of application using a utility for eg on php and mysql we use phpmyadmin what to use for this application any ideas ?

we solved all the issues everything working now lol if u need this contact me il share the repo with you for a fee

**Comment by tbraeutigam** [comment]
Had this issue as well.
Apparently it's because of two things:
One is the ELK setting being far too high for the used elk instance, and the is the cache being generated with this setting.

My workaround `docker-compose.yml`:
```yml
version: "2"

services:
  php:
    container_name: openloyalty_backend
    image: divante/open-loyalty-fpm
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
        - .env
    environment:
      - frontend_customer_panel_url=http://YOUR-FQDN-HERE:8183/client
      - frontend_password_reset_url=YOUR-FQDN-HERE:8183/client#!/password/reset
    command: bash -c "sed -i s_//localhost_//YOUR-FQDN-HERE_g\;s_2000000_9999_g /var/www/openloyalty/app/config/parameters.yml && rm -rf /var/www/openloyalty/var/cache/* && cd /var/www/openloyalty && ./init.sh"
  nginx:
    container_name: openloyalty_frontend
    image: divante/open-loyalty-web
    links:
      - php
    ports:
      - "80:80"
      - "8182:3001"
      - "8183:3002"
      - "8184:3003"
    command: bash -c "sed -i -e 's@"http://openloyalty.localhost/api"@'\"http://YOUR-FQDN-HERE/api\"'@g' /var/www/openloyalty/front/config.js && nginx -g 'daemon off;'"
  elk:
    container_name: openloyalty_elk
    image: elasticsearch:2.2
  db:
    container_name: openloyalty_db
    image: postgres:9
    env_file:
        - .env
  mail:
    container_name: openloyalty_mail
    image: mailhog/mailhog
    ports:
      - "8186:8025"
```

Replace the `YOUR-FQDN-HERE` with your domain, of course.
