### ISSUE TITLE
database update fails

### ISSUE THREAD

**Issue by dolphinsd** [DivanteLtd/open-loyalty#67]
How do I know what database it tries to connect to? Seems to fail:
I checked parameters.yml

vlad@VLAD-PC:/mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend$ php phing.phar setup
Buildfile: /mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/build.xml

OLOY > generate-jwt-keys:

     [echo] JWT tokens already exist in app/var/jwt/!

OLOY > setup:

  [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] No such file or directory

  [PDOException]
  SQLSTATE[HY000] [2002] No such file or directory

doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

BUILD FAILED
/mnt/c/Dev/TestLoyalty/Repo/open-loyalty/backend/build.xml:23:43: Task exited with code 1
Total time: 16.0256 seconds

**Comment by tjurczak** [comment]
Hi @dolphinsd,

OL tries to connect to database which is defined in parameters.yml. Bellow is default configuration:
```
parameters:
    database_host: db
    database_port: null
    database_name: openloyalty
    database_user: openloyalty
    database_password: openloyalty
```
After changing this file reload symfony cache is required.
